from sqlmodel import Session, select
from fastapi import HTTPException, status
from app.db.models import User
from app.core.security import hash_password, verify_password, create_access_token
from app.schemas.auth_schema import RegisterRequest, LoginRequest


def register_user(request: RegisterRequest, session: Session) -> User:
    """
    Create a new user account.

    Steps:
    1. Check the username isn't already taken
    2. Hash the password (never store plaintext)
    3. Assign a unique tenant_id (auto-generated by the model default)
    4. Persist and return the new user
    """
    existing = session.exec(
        select(User).where(User.username == request.username)
    ).first()

    if existing:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already taken. Please choose a different one.",
        )

    user = User(
        username=request.username,
        hashed_password=hash_password(request.password),
        role=request.role,
        # tenant_id is generated automatically via Field(default_factory=uuid4)
    )
    session.add(user)
    session.commit()
    session.refresh(user)  # loads the auto-generated id back from the DB
    return user


def login_user(request: LoginRequest, session: Session) -> str:
    """
    Validate credentials and return a signed JWT.

    Security note: we give the same generic error whether the username
    doesn't exist or the password is wrong — prevents user enumeration.
    """
    user = session.exec(
        select(User).where(User.username == request.username)
    ).first()

    if not user or not verify_password(request.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password.",
        )

    # Pack identity info into the token so downstream routes don't need DB lookups
    token = create_access_token({
        "user_id": user.id,
        "tenant_id": user.tenant_id,
        "role": user.role,
    })
    return token
